import { Inject, Injectable, Optional } from '@nestjs/common';
import { assertSameTenant, type Id, makeEvent, sameTenantOrNull } from '@aura/shared';
import { AuditService, EVENT_STORE, type EventStore, TenantContext } from '@aura/core';
import { ContractService } from './contract.service';
import { CONTRACT_REVISION_STORE, type ContractRevisionStore } from './contract-revision-store';
import { assertRevisionTransition, makeContractRevision, signedRevision, type ContractRevision, type ContractRevisionStatus } from './domain/contract-revision';
import { ContractApprovalService } from './contract-approval.service';

@Injectable()
export class ContractRevisionService {
  constructor(@Inject(CONTRACT_REVISION_STORE) private readonly store: ContractRevisionStore, @Inject(EVENT_STORE) private readonly events: EventStore, private readonly contracts: ContractService, @Optional() @Inject(TenantContext) private readonly tenant: TenantContext|null = null, @Optional() @Inject(AuditService) private readonly audit: AuditService|null = null, @Optional() @Inject(ContractApprovalService) private readonly approvals: ContractApprovalService|null = null) {}
  async submitForApproval(id: Id, actorId: Id|null) { const r=await this.get(id); if(!r) throw new Error(`contract revision ${id} not found`); if(!actorId) throw new Error('approval submission requires an actor'); if(r.status!=='negotiation') throw new Error('only a negotiated revision can be submitted for approval'); return this.approvals?.submit({tenantId:r.tenantId,contractId:r.contractId,target:'revision',targetId:r.id,actorId}) ?? null; }
  async submitForApprovalForContract(contractId: Id, id: Id, actorId: Id|null) { const r=await this.get(id); if(!r || r.contractId!==contractId) throw new Error('contract revision does not belong to contract'); return this.submitForApproval(id, actorId); }
  async decideApproval(id: Id, status: 'approved'|'returned'|'rejected', actorId: Id|null, comment?: string) { const r=await this.get(id); if(!r) throw new Error(`contract revision ${id} not found`); if(status==='approved'&&actorId===r.createdBy) throw new Error('revision author cannot approve their own revision'); if(!this.approvals) throw new Error('canonical approval service unavailable'); await this.approvals.decide('revision',id,status,actorId,comment); if(status==='approved') return this.transition(id,'approved',actorId); if(status==='returned') return this.transition(id,'returned',actorId); return this.transition(id,'rejected',actorId); }
  async decideApprovalForContract(contractId: Id, id: Id, status: 'approved'|'returned'|'rejected', actorId: Id|null, comment?: string) { const r=await this.get(id); if(!r || r.contractId!==contractId) throw new Error('contract revision does not belong to contract'); return this.decideApproval(id,status,actorId,comment); }
  async create(input: Parameters<typeof makeContractRevision>[0]): Promise<ContractRevision> { const c=await this.contracts.get(input.contractId); if(!c) throw new Error(`contract ${input.contractId} not found`); if(c.tenantId!==input.tenantId) throw new Error('contract belongs to another tenant'); const prior=await this.store.list(input.tenantId,input.contractId); const r=makeContractRevision({...input, revisionNumber: input.revisionNumber ?? (prior.reduce((m,x)=>Math.max(m,x.revisionNumber),0)+1), parentRevisionId: input.parentRevisionId ?? prior.at(-1)?.id ?? null}); await this.store.create(r); await this.events.append([makeEvent({type:'contracts.contract.revision.created',tenantId:r.tenantId,companyId:c.companyId,actorId:r.createdBy,aggregateType:'contracts.contract.revision',aggregateId:r.id,payload:{contractId:r.contractId,revisionNumber:r.revisionNumber,parentRevisionId:r.parentRevisionId}})]); await this.audit?.log(r.tenantId,c.companyId,r.createdBy,'contracts','contract_revision',r.id,'created',{revisionNumber:r.revisionNumber},{contractId:r.contractId}); return r; }
  async list(contractId: Id): Promise<ContractRevision[]> { const t=this.tenant?.boundTenantId(); if(!t) return []; return this.store.list(t,contractId); }
  async get(id: Id): Promise<ContractRevision|null> { return sameTenantOrNull(await this.store.get(id),this.tenant?.boundTenantId()); }
  async transitionForContract(contractId: Id, id: Id, status: ContractRevisionStatus, actorId: Id|null): Promise<ContractRevision> {
    const r = await this.get(id);
    if (!r) throw new Error(`contract revision ${id} not found`);
    if (r.contractId !== contractId) throw new Error('contract revision does not belong to contract');
    return this.transition(id, status, actorId);
  }
  async transition(id: Id, status: ContractRevisionStatus, actorId: Id|null): Promise<ContractRevision> { const r=assertSameTenant(await this.store.get(id),this.tenant?.boundTenantId(),'contract revision',id); assertRevisionTransition(r.status,status); if(r.status===status) return r; if ((status === 'approved' || status === 'signed') && !actorId) throw new Error(`${status} transition requires an actor`); if (status === 'approved' && actorId === r.createdBy) throw new Error('revision author cannot approve their own revision'); const now=new Date().toISOString(); const next=status==='signed' ? signedRevision(r,actorId ?? '') : {...r,status, ...(status==='approved' ? {approvedBy:actorId,approvedAt:now} : {})}; await this.store.update(next); await this.events.append([makeEvent({type:`contracts.contract.revision.${status}`,tenantId:r.tenantId,companyId:null,actorId,aggregateType:'contracts.contract.revision',aggregateId:r.id,payload:{contractId:r.contractId,revisionNumber:r.revisionNumber,status}})]); await this.audit?.log(r.tenantId,null,actorId,'contracts','contract_revision',r.id,status,{from:r.status,to:status},{contractId:r.contractId,revisionNumber:r.revisionNumber}); return next; }
}
