import { Inject, Injectable, Optional } from '@nestjs/common';
import { assertSameTenant, type Id, makeEvent } from '@aura/shared';
import { AuditService, EVENT_STORE, type EventStore, TenantContext } from '@aura/core';
import { ContractRevisionService } from './contract-revision.service';
import { ContractApprovalService } from './contract-approval.service';
import { CONTRACT_AMENDMENT_STORE, type ContractAmendmentStore } from './contract-amendment-store';
import { assertAmendmentTransition, makeContractAmendment, type ContractAmendmentStatus, type NewContractAmendment } from './domain/contract-amendment';

@Injectable()
export class ContractAmendmentService {
  constructor(@Inject(CONTRACT_AMENDMENT_STORE) private readonly store: ContractAmendmentStore, @Inject(EVENT_STORE) private readonly events: EventStore, private readonly revisions: ContractRevisionService, @Optional() @Inject(TenantContext) private readonly tenant: TenantContext|null = null, @Optional() @Inject(ContractApprovalService) private readonly approvals: ContractApprovalService|null = null, @Optional() @Inject(AuditService) private readonly audit: AuditService|null = null) {}
  async create(input: NewContractAmendment) { const r=await this.revisions.get(input.baseRevisionId); if(!r||r.contractId!==input.contractId||r.tenantId!==input.tenantId)throw new Error('base revision does not belong to contract'); if(r.status!=='signed')throw new Error('amendment requires a signed base revision'); const prior=await this.store.list(input.tenantId,input.contractId); const a=makeContractAmendment({...input,amendmentNumber:input.amendmentNumber??(prior.reduce((m,x)=>Math.max(m,x.amendmentNumber),0)+1)}); await this.store.create(a); await this.events.append([makeEvent({type:'contracts.contract.amendment.created',tenantId:a.tenantId,companyId:null,actorId:a.createdBy,aggregateType:'contracts.contract',aggregateId:a.contractId,payload:{amendmentId:a.id,amendmentNumber:a.amendmentNumber,baseRevisionId:a.baseRevisionId}})]); await this.audit?.log(a.tenantId,null,a.createdBy,'contracts','contract_amendment',a.id,'created',{amendmentNumber:a.amendmentNumber},{contractId:a.contractId}); return a; }
  async list(contractId:Id){const t=this.tenant?.boundTenantId();return t?this.store.list(t,contractId):[];}
  async submitForApproval(id:Id,actorId:Id|null){const a=await this.getOwned(id); if(!actorId)throw new Error('approval submission requires an actor'); if(a.status!=='review')throw new Error('only a reviewed amendment can be submitted for approval'); return this.approvals?.submit({tenantId:a.tenantId,contractId:a.contractId,target:'amendment',targetId:a.id,actorId}) ?? null;}
  async submitForApprovalForContract(contractId:Id,id:Id,actorId:Id|null){const a=await this.getOwned(id);if(a.contractId!==contractId)throw new Error('amendment does not belong to contract');return this.submitForApproval(id,actorId);}
  async decideApproval(id:Id,status:'approved'|'returned'|'rejected',actorId:Id|null,comment?:string){const a=await this.getOwned(id);if(status==='approved'&&actorId===a.createdBy)throw new Error('amendment author cannot approve their own amendment');if(!this.approvals)throw new Error('canonical approval service unavailable'); await this.approvals.decide('amendment',id,status,actorId,comment); return this.transition(id,status,actorId);}
  async decideApprovalForContract(contractId:Id,id:Id,status:'approved'|'returned'|'rejected',actorId:Id|null,comment?:string){const a=await this.getOwned(id);if(a.contractId!==contractId)throw new Error('amendment does not belong to contract');return this.decideApproval(id,status,actorId,comment);}
  async transition(id:Id,status:ContractAmendmentStatus,actorId:Id|null){const a=await this.getOwned(id);assertAmendmentTransition(a.status,status);if((status==='approved'||status==='signed')&&!actorId)throw new Error(`${status} transition requires an actor`);if(status==='approved'&&actorId===a.createdBy)throw new Error('amendment author cannot approve their own amendment');const now=new Date().toISOString();const n={...a,status,...(status==='approved'?{approvedBy:actorId,approvedAt:now}:{}),...(status==='signed'?{signedBy:actorId,signedAt:now}: {})};await this.store.update(n);await this.events.append([makeEvent({type:`contracts.contract.amendment.${status}`,tenantId:a.tenantId,companyId:null,actorId,aggregateType:'contracts.contract',aggregateId:a.contractId,payload:{amendmentId:a.id,status}})]);await this.audit?.log(a.tenantId,null,actorId,'contracts','contract_amendment',a.id,status,{from:a.status,to:status},{contractId:a.contractId});return n;}
  private async getOwned(id:Id){return assertSameTenant(await this.store.get(id),this.tenant?.boundTenantId(),'contract amendment',id);}
}
