import { Inject, Injectable, Optional } from '@nestjs/common';
import { AuditService, ApprovalMatrixService, EVENT_STORE, type EventStore, TenantContext, AccessService } from '@aura/core';
import { makeEvent, type Id } from '@aura/shared';
import { CONTRACT_APPROVAL_STORE, type ContractApprovalStore } from './contract-approval-store';
import { makeContractApproval, type ContractApproval, type ContractApprovalStatus, type ContractApprovalTarget } from './domain/contract-approval';

@Injectable()
export class ContractApprovalService {
  constructor(@Inject(CONTRACT_APPROVAL_STORE) private readonly store:ContractApprovalStore, @Inject(EVENT_STORE) private readonly events:EventStore, @Optional() @Inject(AccessService) private readonly access:AccessService|null=null, @Optional() @Inject(ApprovalMatrixService) private readonly matrix:ApprovalMatrixService|null=null, @Optional() @Inject(AuditService) private readonly audit:AuditService|null=null, @Optional() @Inject(TenantContext) private readonly tenant:TenantContext|null=null) {}
  async get(target:ContractApprovalTarget,targetId:Id):Promise<ContractApproval|null>{const t=this.tenant?.boundTenantId(); return t?this.store.get(t,target,targetId):null;}
  async submit(input:{tenantId:Id;contractId:Id;target:ContractApprovalTarget;targetId:Id;actorId:Id|null}):Promise<ContractApproval>{const existing=await this.store.get(input.tenantId,input.target,input.targetId); if(existing)return existing; const a=makeContractApproval({tenantId:input.tenantId,contractId:input.contractId,target:input.target,targetId:input.targetId,submittedBy:input.actorId}); try { await this.store.create(a); } catch (e) { const concurrent=await this.store.get(input.tenantId,input.target,input.targetId); if(concurrent)return concurrent; throw e; } await this.events.append([makeEvent({type:'contracts.contract.approval.submitted',tenantId:a.tenantId,companyId:null,actorId:input.actorId,aggregateType:`contracts.${input.target}.approval`,aggregateId:a.id,payload:{contractId:a.contractId,target:a.target,targetId:a.targetId}})]); await this.audit?.log(a.tenantId,null,input.actorId,'contracts','contract_approval',a.id,'submitted',{target:a.target,targetId:a.targetId}); return a;}
  async decide(target:ContractApprovalTarget,targetId:Id,status:Extract<ContractApprovalStatus,'approved'|'returned'|'rejected'>,actorId:Id|null,comment?:string){if(!actorId)throw new Error('approval decision requires an actor'); const a=await this.get(target,targetId); if(!a)throw new Error('approval not submitted'); if(a.submittedBy&&a.submittedBy===actorId)throw new Error('approval author cannot approve their own submission'); if(this.matrix){const decision=await this.matrix.resolve(a.tenantId,`contracts.${target}.approval`,{contractId:a.contractId,targetId}); if(decision?.approvers.length && !decision.approvers.includes(actorId))throw new Error('actor is not an approver for this contract approval');} if(this.access){try{this.access.assert(actorId,{permission:`contracts.${target}.approve`,orgPath:[{level:'tenant',id:a.tenantId}],resource:{type:`contracts.${target}`,id:targetId}});}catch(e){if((e as Error).message)throw e;}} const next=await this.store.decide(a,status,actorId,comment); await this.events.append([makeEvent({type:`contracts.contract.approval.${status}`,tenantId:a.tenantId,companyId:null,actorId,aggregateType:`contracts.${target}.approval`,aggregateId:a.id,payload:{contractId:a.contractId,target,targetId,status,comment:comment||null}})]); await this.audit?.log(a.tenantId,null,actorId,'contracts','contract_approval',a.id,status,{target,targetId,comment:comment||null},{contractId:a.contractId}); return next;}
}
