import type { Pool } from 'pg';
import type { Id } from '@aura/shared';
import type { ContractRevision, ContractRevisionClause } from './domain/contract-revision';
import type { ContractRevisionStore } from './contract-revision-store';
const COLS = 'id, tenant_id, contract_id, revision_number, parent_revision_id, status, revision_reason, terms, clauses, created_by, created_at, approved_by, approved_at, signed_by, signed_at';
type Row = { id:string; tenant_id:string; contract_id:string; revision_number:number; parent_revision_id:string|null; status:string; revision_reason:string|null; terms:unknown; clauses:unknown; created_by:string|null; created_at:Date|string; approved_by:string|null; approved_at:Date|string|null; signed_by:string|null; signed_at:Date|string|null };
const iso = (v: Date|string|null): string|null => v === null ? null : v instanceof Date ? v.toISOString() : String(v);
const from = (r: Row): ContractRevision => ({ id:r.id, tenantId:r.tenant_id, contractId:r.contract_id, revisionNumber:Number(r.revision_number), parentRevisionId:r.parent_revision_id, status:r.status as ContractRevision['status'], revisionReason:r.revision_reason, terms:(typeof r.terms === 'string' ? JSON.parse(r.terms) : r.terms ?? {}) as Record<string, unknown>, clauses:(typeof r.clauses === 'string' ? JSON.parse(r.clauses) : r.clauses ?? []) as ContractRevisionClause[], createdBy:r.created_by, createdAt:iso(r.created_at)!, approvedBy:r.approved_by, approvedAt:iso(r.approved_at), signedBy:r.signed_by, signedAt:iso(r.signed_at) });
export class PostgresContractRevisionStore implements ContractRevisionStore {
  constructor(private readonly pool: Pool) {}
  async create(r: ContractRevision): Promise<void> { await this.pool.query(`INSERT INTO public.aura_contracts_revisions (${COLS}) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)`, [r.id,r.tenantId,r.contractId,r.revisionNumber,r.parentRevisionId,r.status,r.revisionReason,JSON.stringify(r.terms),JSON.stringify(r.clauses),r.createdBy,r.createdAt,r.approvedBy,r.approvedAt,r.signedBy,r.signedAt]); }
  async get(id: Id): Promise<ContractRevision|null> { const q=await this.pool.query<Row>(`SELECT ${COLS} FROM public.aura_contracts_revisions WHERE id=$1`,[id]); return q.rows[0] ? from(q.rows[0]) : null; }
  async list(tenantId: Id, contractId: Id): Promise<ContractRevision[]> { const q=await this.pool.query<Row>(`SELECT ${COLS} FROM public.aura_contracts_revisions WHERE tenant_id=$1 AND contract_id=$2 ORDER BY revision_number`,[tenantId,contractId]); return q.rows.map(from); }
  async update(r: ContractRevision): Promise<void> { const old=await this.get(r.id); if (old?.status==='signed' && JSON.stringify(old)!==JSON.stringify(r)) throw new Error('signed contract revision is immutable'); const result=await this.pool.query(`UPDATE public.aura_contracts_revisions SET status=$2, revision_reason=$3, terms=$4, clauses=$5, approved_by=$6, approved_at=$7, signed_by=$8, signed_at=$9 WHERE id=$1 AND tenant_id=$10 AND status=$11`,[r.id,r.status,r.revisionReason,JSON.stringify(r.terms),JSON.stringify(r.clauses),r.approvedBy,r.approvedAt,r.signedBy,r.signedAt,r.tenantId,old?.status]); if (result.rowCount !== 1) throw new Error('contract revision changed concurrently'); }
}
