import * as XLSX from 'xlsx';
import { describe, expect, it } from 'vitest';
import { buildWorkbook, typedCell, type WorkbookColumn } from './workbook';

interface Row { name: string; amount: number | null; qty: number; since: string; at: string; active: boolean }

const COLUMNS: WorkbookColumn<Row>[] = [
  { label: 'Name', type: 'text', value: (r) => r.name },
  { label: 'Amount', type: 'money', value: (r) => r.amount, total: true },
  { label: 'Qty', type: 'integer', value: (r) => r.qty, total: true },
  { label: 'Since', type: 'date', value: (r) => r.since },
  { label: 'Updated', type: 'datetime', value: (r) => r.at },
  { label: 'Active', type: 'boolean', value: (r) => r.active },
];
const ROWS: Row[] = [
  { name: 'Alpha', amount: 0.1, qty: 2, since: '2026-01-15', at: '2026-10-01T20:30:00Z', active: true },
  { name: 'Beta', amount: 0.2, qty: 3, since: '2026-02-01', at: '2026-10-02T04:00:00Z', active: false },
  { name: 'Gamma', amount: null, qty: 5, since: '', at: '', active: true },
];
const LINEAGE = {
  title: 'Probe register', source: 'Probe register (test)', completeness: 'All 3 rows you are permitted to see.',
  filters: [['Status', 'active']] as Array<[string, string]>, generatedAt: '2 Oct 2026, 10:00 (Asia/Dubai)', generatedBy: 'u-tester',
  issuer: ['Probe Holding L.L.C.', 'TRN 100111111111111'], currency: 'AED',
};

describe('the governed workbook', () => {
  const bytes = buildWorkbook('Register', COLUMNS, ROWS, LINEAGE);
  const book = XLSX.read(bytes, { type: 'buffer', cellFormula: true, cellNF: true });
  const data = book.Sheets.Register;

  it('is a native xlsx with the data first and the lineage after', () => {
    expect(bytes.subarray(0, 2).toString('latin1')).toBe('PK');
    expect(book.SheetNames).toEqual(['Register', 'About this export']);
  });

  it('types its cells: numbers as numbers with formats, dates as dates, empty as empty', () => {
    expect(data.B2).toMatchObject({ t: 'n', v: 0.1, z: '#,##0.00' });
    expect(data.C3).toMatchObject({ t: 'n', v: 3, z: '#,##0' });
    // 2026-01-15 is Excel serial 46037.
    expect(data.D2).toMatchObject({ t: 'n', v: 46037, z: 'yyyy-mm-dd' });
    // 20:30Z is 00:30 the next day on the Dubai wall clock — the reader's time, not UTC.
    expect(data.E2.t).toBe('n');
    expect(XLSX.SSF.format('yyyy-mm-dd hh:mm', data.E2.v as number)).toBe('2026-10-02 00:30');
    expect(data.F3).toMatchObject({ t: 'b', v: false });
    expect(data.B4, 'an absent amount is an empty cell, not the text ""').toBeUndefined();
    expect(data.D4).toBeUndefined();
  });

  it('filters the header and data, and totals only what is summable, following the filter', () => {
    expect(data['!autofilter']?.ref).toBe('A1:F4');
    expect(data.A5).toMatchObject({ t: 's', v: 'Total' });
    // 0.1 + 0.2 summed by the money authority: 0.3, not 0.30000000000000004.
    expect(data.B5).toMatchObject({ t: 'n', v: 0.3, f: 'SUBTOTAL(109,B2:B4)' });
    expect(data.C5).toMatchObject({ t: 'n', v: 10, f: 'SUBTOTAL(109,C2:C4)' });
    expect(data.D5).toBeUndefined();
  });

  it('says where it came from, under whom, and how complete it is', () => {
    const about = XLSX.utils.sheet_to_json<string[]>(book.Sheets['About this export'], { header: 1 });
    const field = (name: string) => about.find((row) => row[0] === name)?.[1];
    expect(field('Source')).toBe('Probe register (test)');
    expect(field('Rows')).toBe('3');
    expect(field('Completeness')).toBe('All 3 rows you are permitted to see.');
    expect(field('Filter: Status')).toBe('active');
    expect(field('Generated by')).toBe('u-tester');
    expect(field('Issued under')).toBe('Probe Holding L.L.C. · TRN 100111111111111');
  });

  it('freezes the header row of the data sheet', () => {
    const CFB = (XLSX as unknown as { CFB: { read: (b: Buffer, o: object) => unknown; find: (c: unknown, p: string) => { content: Uint8Array } | null } }).CFB;
    const zip = CFB.read(bytes, { type: 'buffer' });
    const sheet = Buffer.from(CFB.find(zip, '/xl/worksheets/sheet1.xml')!.content).toString('utf8');
    expect(sheet).toContain('<pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/>');
  });

  it('keeps unparseable values as text rather than inventing a number or a date', () => {
    expect(typedCell('money', 'n/a')).toEqual({ t: 's', v: 'n/a' });
    expect(typedCell('date', 'soon')).toEqual({ t: 's', v: 'soon' });
    expect(typedCell('money', '1,250.50')).toMatchObject({ t: 'n', v: 1250.5 });
  });
});
