import { describe, it, expect, vi } from 'vitest';
import type { EventStore } from '@aura/core';
import { CustomerInvoiceService } from './customer-invoice.service';
import { InMemoryCustomerInvoiceStore } from './in-memory-customer-invoice-store';
import type { NewCustomerInvoice } from './domain/customer-invoice';

// Per-tenant uniqueness of the (user-supplied) AR invoice number. AP references are generated by
// the numbering service and are unique by construction; AR numbers are typed in, so the service is
// what stops two invoices sharing one.

const events = () => ({ append: vi.fn().mockResolvedValue(undefined) }) as unknown as EventStore;
const A = 'tenant-a';
const B = 'tenant-b';

function harness() {
  const store = new InMemoryCustomerInvoiceStore();
  const append = vi.fn().mockResolvedValue(undefined);
  const svc = new CustomerInvoiceService(store, { append } as any, {} as any, {} as any, {} as any);
  const input = (tenantId: string, invoiceNumber: string): NewCustomerInvoice => ({
    tenantId, invoiceNumber, customerName: 'Acme', issueDate: '2026-01-10',
    lines: [{ description: 'work', quantity: 1, unitPrice: 1000 }],
  });
  return { store, svc, input, append };
}

const emittedTypes = (append: ReturnType<typeof vi.fn>): string[] =>
  append.mock.calls.flatMap((c) => (c[0] as Array<{ type: string }>).map((e) => e.type));

describe('CustomerInvoiceService — invoice-number uniqueness', () => {
  it('creates an invoice with a fresh number', async () => {
    const { svc, input } = harness();
    const inv = await svc.create(input(A, 'AR-1'));
    expect(inv.invoiceNumber).toBe('AR-1');
  });

  it('rejects a duplicate number within the same tenant', async () => {
    const { svc, input } = harness();
    await svc.create(input(A, 'AR-1'));
    await expect(svc.create(input(A, 'AR-1'))).rejects.toThrow(/already exists/i);
  });

  it('lets a different tenant use the same number (uniqueness is per tenant)', async () => {
    const { svc, input } = harness();
    await svc.create(input(A, 'AR-1'));
    const b = await svc.create(input(B, 'AR-1'));
    expect(b.tenantId).toBe(B);
  });

  it('frees the number once the original is soft-deleted', async () => {
    const { svc, input } = harness();
    const first = await svc.create(input(A, 'AR-1'));
    await svc.softDelete(A, first.id);
    const reissued = await svc.create(input(A, 'AR-1')); // number is free again
    expect(reissued.id).not.toBe(first.id);
  });
});

describe('CustomerInvoiceService — audit trail', () => {
  it('emits a cancelled event when a receivable is voided', async () => {
    // Cancelling an invoice is an auditable financial act; it used to save silently with no spine
    // event, unlike create/issue/receipt.
    const { svc, input, append } = harness();
    const inv = await svc.create(input(A, 'AR-1'));
    await svc.cancel(inv.id);
    expect(emittedTypes(append)).toContain('finance.customer_invoice.cancelled');
  });
});
