'use client';

import { useEffect, useState } from 'react';
import type { CSSProperties } from 'react';

// Accounts register — A4 print sheet of every CRM account (browser print-to-PDF).

interface Account {
  id: string;
  name: string;
  status: string;
  industry: string | null;
  phone: string | null;
  email: string | null;
  source: string | null;
  paymentTerms: string | null;
  createdAt: string;
}

const d = (iso: string): string => new Date(iso).toLocaleDateString('en-GB');

export default function AccountsRegisterPrint() {
  const [rows, setRows] = useState<Account[] | null>(null);

  useEffect(() => {
    void (async () => {
      const res = await fetch('/api/crm/accounts', { cache: 'no-store' });
      if (res.ok) {
        const data = await res.json();
        setRows(Array.isArray(data) ? data : (data.items ?? []));
      }
    })();
  }, []);

  if (!rows) return <p style={{ padding: 24, color: '#666' }}>Preparing register…</p>;

  return (
    <div style={s.wrap}>
      <style>{PRINT_CSS}</style>
      <div className="no-print" style={s.toolbar}>
        <button type="button" style={s.printBtn} onClick={() => window.print()}>🖨 Print / Save as PDF</button>
        <button type="button" style={s.backBtn} onClick={() => window.history.back()}>← Back</button>
      </div>

      <div className="sheet" style={s.sheet}>
        <header style={s.header}>
          <div>
            <div style={s.company}>AURA OS Contracting LLC</div>
            <div style={s.companyMeta}>Dubai, United Arab Emirates · TRN 100000000000003</div>
          </div>
          <div style={{ textAlign: 'right' }}>
            <div style={s.kind}>CRM · ACCOUNTS REGISTER</div>
            <div style={s.ref}>{rows.length} account{rows.length === 1 ? '' : 's'}</div>
          </div>
        </header>

        <table style={s.table}>
          <thead>
            <tr>
              {['Account', 'Status', 'Industry', 'Phone', 'Email', 'Source', 'Payment terms', 'Client since'].map((h, i) => (
                <th key={i} style={s.th}>{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {rows.map((a) => (
              <tr key={a.id}>
                <td style={{ ...s.td, fontWeight: 600 }}>{a.name}</td>
                <td style={{ ...s.td, textTransform: 'capitalize' }}>{a.status}</td>
                <td style={s.td}>{a.industry ?? '—'}</td>
                <td style={s.td}>{a.phone ?? '—'}</td>
                <td style={s.td}>{a.email ?? '—'}</td>
                <td style={s.td}>{a.source ?? '—'}</td>
                <td style={s.td}>{a.paymentTerms ?? '—'}</td>
                <td style={s.td}>{d(a.createdAt)}</td>
              </tr>
            ))}
          </tbody>
        </table>

        <footer style={s.footer}>Generated by AURA OS · {new Date().toLocaleString('en-GB')} · INTERNAL</footer>
      </div>
    </div>
  );
}

const PRINT_CSS = `
@page { size: A4 landscape; margin: 12mm; }
@media print {
  .no-print { display: none !important; }
  body { background: #fff !important; }
  .sheet { box-shadow: none !important; margin: 0 !important; border: none !important; }
}
`;

const s = {
  wrap: { maxWidth: 1080, margin: '0 auto', padding: 16 } as CSSProperties,
  toolbar: { display: 'flex', gap: 8, marginBottom: 12 } as CSSProperties,
  printBtn: { background: 'var(--accent, #2563eb)', color: '#fff', border: 'none', borderRadius: 8, padding: '9px 14px', fontSize: 13.5, cursor: 'pointer', fontWeight: 600 } as CSSProperties,
  backBtn: { background: 'transparent', border: '1px solid var(--border, #d0d5dd)', borderRadius: 8, padding: '9px 14px', fontSize: 13.5, cursor: 'pointer', color: 'var(--text, #111)' } as CSSProperties,
  sheet: { background: '#fff', color: '#111', border: '1px solid #e5e7eb', borderRadius: 4, padding: '28px 32px', boxShadow: '0 1px 8px rgba(0,0,0,0.08)', fontSize: 12.5 } as CSSProperties,
  header: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', borderBottom: '2px solid #111', paddingBottom: 14, marginBottom: 16 } as CSSProperties,
  company: { fontSize: 18, fontWeight: 700 } as CSSProperties,
  companyMeta: { fontSize: 11, color: '#555', marginTop: 3 } as CSSProperties,
  kind: { fontSize: 15, fontWeight: 700, letterSpacing: 0.5 } as CSSProperties,
  ref: { fontSize: 12, color: '#555', marginTop: 2 } as CSSProperties,
  table: { width: '100%', borderCollapse: 'collapse', fontSize: 11.5 } as CSSProperties,
  th: { textAlign: 'left', borderBottom: '1.5px solid #111', padding: '6px 8px', fontSize: 10, textTransform: 'uppercase', color: '#333' } as CSSProperties,
  td: { padding: '6px 8px', borderBottom: '1px solid #eee' } as CSSProperties,
  footer: { marginTop: 24, paddingTop: 10, borderTop: '1px solid #eee', fontSize: 10, color: '#999', textAlign: 'center' } as CSSProperties,
};
