'use client';

import { useMemo, useState, type CSSProperties } from 'react';
import EmptyState from './ui/empty-state';

export interface Campaign {
  id: string;
  name: string;
  channel: string;
  status: 'planned' | 'active' | 'completed';
  budget: number;
  startDate: string | null;
  endDate: string | null;
  targetLeads: number;
  leadsGenerated: number;
  wonValue: number;
  notes: string | null;
  createdAt: string;
  metrics: { roi: number | null; costPerLead: number | null };
}

const CHANNELS = ['email', 'event', 'referral', 'web', 'social', 'paid_ads', 'other'];
const STATUSES: Campaign['status'][] = ['planned', 'active', 'completed'];
const money = (n: number) => `AED ${Math.round(n).toLocaleString()}`;
const pct = (n: number | null) => (n == null ? '—' : `${Math.round(n * 100)}%`);

export default function CampaignsClient({ initial }: { initial: Campaign[] }) {
  const [rows, setRows] = useState<Campaign[]>(initial);
  const [busy, setBusy] = useState(false);
  const [form, setForm] = useState({ name: '', channel: 'email', budget: '', targetLeads: '' });

  const totals = useMemo(() => {
    const spend = rows.reduce((s, c) => s + c.budget, 0);
    const won = rows.reduce((s, c) => s + c.wonValue, 0);
    const leads = rows.reduce((s, c) => s + c.leadsGenerated, 0);
    return { spend, won, leads, roi: spend > 0 ? (won - spend) / spend : null };
  }, [rows]);

  async function create() {
    if (!form.name.trim() || busy) return;
    setBusy(true);
    try {
      const res = await fetch('/api/crm/campaigns', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({
          name: form.name.trim(),
          channel: form.channel,
          budget: Number(form.budget) || 0,
          targetLeads: Number(form.targetLeads) || 0,
        }),
      });
      const created = (await res.json()) as Campaign;
      if (res.ok && created?.id) {
        setRows((r) => [created, ...r]);
        setForm({ name: '', channel: 'email', budget: '', targetLeads: '' });
      }
    } finally {
      setBusy(false);
    }
  }

  async function patch(id: string, path: 'results' | 'status', body: Record<string, unknown>) {
    const res = await fetch(`/api/crm/campaigns/${id}/${path}`, {
      method: 'PATCH',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify(body),
    });
    const updated = (await res.json()) as Campaign;
    if (res.ok && updated?.id) setRows((r) => r.map((c) => (c.id === id ? updated : c)));
  }

  async function recordResults(c: Campaign) {
    const leads = window.prompt(`Leads generated by "${c.name}"?`, String(c.leadsGenerated));
    if (leads == null) return;
    const won = window.prompt(`Won revenue attributed to "${c.name}" (AED)?`, String(c.wonValue));
    if (won == null) return;
    await patch(c.id, 'results', { leadsGenerated: Number(leads) || 0, wonValue: Number(won) || 0 });
  }

  return (
    <div>
      <div style={st.kpis}>
        <Kpi label="Total spend" value={money(totals.spend)} />
        <Kpi label="Attributed won" value={money(totals.won)} />
        <Kpi label="Leads generated" value={String(totals.leads)} />
        <Kpi label="Blended ROI" value={pct(totals.roi)} accent={totals.roi != null && totals.roi >= 0} />
      </div>

      <div style={st.form}>
        <input
          style={st.input}
          placeholder="Campaign name"
          value={form.name}
          onChange={(e) => setForm({ ...form, name: e.target.value })}
          onKeyDown={(e) => e.key === 'Enter' && create()}
        />
        <select style={st.input} value={form.channel} onChange={(e) => setForm({ ...form, channel: e.target.value })}>
          {CHANNELS.map((c) => (
            <option key={c} value={c}>{c.replace('_', ' ')}</option>
          ))}
        </select>
        <input
          style={{ ...st.input, width: 130 }}
          placeholder="Budget (AED)"
          inputMode="numeric"
          value={form.budget}
          onChange={(e) => setForm({ ...form, budget: e.target.value })}
        />
        <input
          style={{ ...st.input, width: 120 }}
          placeholder="Target leads"
          inputMode="numeric"
          value={form.targetLeads}
          onChange={(e) => setForm({ ...form, targetLeads: e.target.value })}
        />
        <button style={st.btn} onClick={create} disabled={busy || !form.name.trim()}>
          {busy ? 'Adding…' : 'Add campaign'}
        </button>
      </div>

      {rows.length === 0 ? (
        <EmptyState
          title="No campaigns yet"
          description="Add your first marketing campaign above to start tracking spend and pipeline ROI."
        />
      ) : (
        <div style={st.tableWrap}>
          <table style={st.table}>
            <thead>
              <tr>
                <th style={st.th}>Campaign</th>
                <th style={st.th}>Channel</th>
                <th style={st.th}>Status</th>
                <th style={st.thR}>Budget</th>
                <th style={st.thR}>Leads</th>
                <th style={st.thR}>Cost/lead</th>
                <th style={st.thR}>Won</th>
                <th style={st.thR}>ROI</th>
                <th style={st.th}></th>
              </tr>
            </thead>
            <tbody>
              {rows.map((c) => (
                <tr key={c.id}>
                  <td style={st.td}>{c.name}</td>
                  <td style={st.td}>{c.channel.replace('_', ' ')}</td>
                  <td style={st.td}>
                    <select
                      style={st.statusSel}
                      value={c.status}
                      onChange={(e) => patch(c.id, 'status', { status: e.target.value })}
                    >
                      {STATUSES.map((s) => (
                        <option key={s} value={s}>{s}</option>
                      ))}
                    </select>
                  </td>
                  <td style={st.tdR}>{money(c.budget)}</td>
                  <td style={st.tdR}>{c.leadsGenerated}{c.targetLeads ? ` / ${c.targetLeads}` : ''}</td>
                  <td style={st.tdR}>{c.metrics.costPerLead == null ? '—' : money(c.metrics.costPerLead)}</td>
                  <td style={st.tdR}>{money(c.wonValue)}</td>
                  <td style={{ ...st.tdR, color: c.metrics.roi == null ? 'var(--muted)' : c.metrics.roi >= 0 ? '#16a34a' : '#dc2626' }}>
                    {pct(c.metrics.roi)}
                  </td>
                  <td style={st.td}>
                    <button style={st.link} onClick={() => recordResults(c)}>Record results</button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}

function Kpi({ label, value, accent }: { label: string; value: string; accent?: boolean }) {
  return (
    <div style={st.kpi}>
      <div style={st.kpiLabel}>{label}</div>
      <div style={{ ...st.kpiValue, color: accent == null ? 'var(--text)' : accent ? '#16a34a' : '#dc2626' }}>{value}</div>
    </div>
  );
}

const st = {
  kpis: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))', gap: 12, marginBottom: 20 } as CSSProperties,
  kpi: { border: '1px solid var(--border)', borderRadius: 10, padding: '14px 16px', background: 'var(--panel)' } as CSSProperties,
  kpiLabel: { fontSize: 12, color: 'var(--muted)', marginBottom: 4 } as CSSProperties,
  kpiValue: { fontSize: 22, fontWeight: 600, letterSpacing: -0.5 } as CSSProperties,
  form: { display: 'flex', flexWrap: 'wrap', gap: 8, marginBottom: 20, alignItems: 'center' } as CSSProperties,
  input: { padding: '8px 10px', borderRadius: 8, border: '1px solid var(--border)', background: 'var(--panel)', color: 'var(--text)', fontSize: 14 } as CSSProperties,
  btn: { padding: '8px 16px', borderRadius: 8, border: 'none', background: 'var(--accent)', color: '#fff', fontSize: 14, cursor: 'pointer', fontWeight: 500 } as CSSProperties,
  tableWrap: { border: '1px solid var(--border)', borderRadius: 10, overflowX: 'auto' } as CSSProperties,
  table: { width: '100%', borderCollapse: 'collapse', fontSize: 14 } as CSSProperties,
  th: { textAlign: 'left', padding: '10px 14px', borderBottom: '1px solid var(--border)', color: 'var(--muted)', fontWeight: 500, fontSize: 12, whiteSpace: 'nowrap' } as CSSProperties,
  thR: { textAlign: 'right', padding: '10px 14px', borderBottom: '1px solid var(--border)', color: 'var(--muted)', fontWeight: 500, fontSize: 12, whiteSpace: 'nowrap' } as CSSProperties,
  td: { padding: '10px 14px', borderBottom: '1px solid var(--border)', whiteSpace: 'nowrap' } as CSSProperties,
  tdR: { padding: '10px 14px', borderBottom: '1px solid var(--border)', textAlign: 'right', whiteSpace: 'nowrap' } as CSSProperties,
  statusSel: { padding: '3px 6px', borderRadius: 6, border: '1px solid var(--border)', background: 'var(--panel)', color: 'var(--text)', fontSize: 13 } as CSSProperties,
  link: { background: 'none', border: 'none', color: 'var(--accent)', cursor: 'pointer', fontSize: 13, padding: 0 } as CSSProperties,
};
