'use client';

import { type CSSProperties } from 'react';

export interface DocColumn {
  key: string;
  label: string;
  align?: 'left' | 'right';
}
export interface DocTotal {
  label: string;
  value: string;
  strong?: boolean;
}
export interface DocMeta {
  label: string;
  value: string;
}
export interface DocParty {
  heading: string;
  lines: string[];
}

export interface DocumentSheetProps {
  kind: string;          // e.g. "TAX INVOICE"
  reference: string;
  status?: string;
  meta: DocMeta[];
  from: DocParty;
  to: DocParty;
  columns?: DocColumn[];
  rows?: Array<Record<string, string | number>>;
  totals?: DocTotal[];
  notes?: string;
  signatures?: string[];
}

/**
 * Reusable A4 print sheet — one presentation for every business document (invoice, PO, GRN,
 * IPC). Renders a letterhead + parties + meta grid + optional line-item table + totals +
 * signatures, with a print CSS (`@page A4`) and a toolbar that hides on print. "Print / Save
 * as PDF" uses the browser's native print-to-PDF (no server dependency).
 */
export default function DocumentSheet(props: DocumentSheetProps) {
  const { kind, reference, status, meta, from, to, columns, rows, totals, notes, signatures } = props;
  return (
    <div style={s.wrap}>
      <style>{PRINT_CSS}</style>

      <div className="no-print" style={s.toolbar}>
        <button type="button" style={s.printBtn} onClick={() => window.print()}>🖨 Print / Save as PDF</button>
        <button type="button" style={s.backBtn} onClick={() => window.history.back()}>← Back</button>
      </div>

      <div className="sheet" style={s.sheet}>
        <header style={s.header}>
          <div>
            <div style={s.company}>AURA OS Contracting LLC</div>
            <div style={s.companyMeta}>Dubai, United Arab Emirates · TRN 100000000000003</div>
          </div>
          <div style={s.docBox}>
            <div style={s.kind}>{kind}</div>
            <div style={s.ref}>{reference}</div>
            {status && <div style={s.status}>{status.replace(/_/g, ' ')}</div>}
          </div>
        </header>

        <section style={s.parties}>
          <Party party={from} />
          <Party party={to} />
        </section>

        {meta.length > 0 && (
          <section style={s.metaGrid}>
            {meta.map((m) => (
              <div key={m.label} style={s.metaItem}>
                <span style={s.metaLabel}>{m.label}</span>
                <span style={s.metaValue}>{m.value}</span>
              </div>
            ))}
          </section>
        )}

        {columns && rows && (
          <table style={s.table}>
            <thead>
              <tr>{columns.map((c) => <th key={c.key} style={c.align === 'right' ? s.thR : s.th}>{c.label}</th>)}</tr>
            </thead>
            <tbody>
              {rows.length === 0 ? (
                <tr><td style={s.td} colSpan={columns.length}>No line items.</td></tr>
              ) : rows.map((r, i) => (
                <tr key={i}>{columns.map((c) => <td key={c.key} style={c.align === 'right' ? s.tdR : s.td}>{String(r[c.key] ?? '')}</td>)}</tr>
              ))}
            </tbody>
          </table>
        )}

        {totals && totals.length > 0 && (
          <section style={s.totals}>
            {totals.map((t) => (
              <div key={t.label} style={t.strong ? s.totalRowStrong : s.totalRow}>
                <span>{t.label}</span><span>{t.value}</span>
              </div>
            ))}
          </section>
        )}

        {notes && <section style={s.notes}><strong>Notes:</strong> {notes}</section>}

        {signatures && signatures.length > 0 && (
          <section style={s.signs}>
            {signatures.map((label) => (
              <div key={label} style={s.sign}><div style={s.signLine} /><div style={s.signLabel}>{label}</div></div>
            ))}
          </section>
        )}

        <footer style={s.footer}>Generated by AURA OS · {new Date().toLocaleString('en-GB')}</footer>
      </div>
    </div>
  );
}

function Party({ party }: { party: DocParty }) {
  return (
    <div style={s.party}>
      <div style={s.partyHeading}>{party.heading}</div>
      {party.lines.map((l, i) => <div key={i} style={i === 0 ? s.partyName : s.partyLine}>{l}</div>)}
    </div>
  );
}

const PRINT_CSS = `
@page { size: A4; margin: 12mm; }
@media print {
  .no-print { display: none !important; }
  body { background: #fff !important; }
  .sheet { box-shadow: none !important; margin: 0 !important; }
}
`;

const s = {
  wrap: { maxWidth: 820, margin: '0 auto', padding: '16px' } as CSSProperties,
  toolbar: { display: 'flex', gap: 8, marginBottom: 12 } as CSSProperties,
  printBtn: { background: 'var(--accent, #2563eb)', color: '#fff', border: 'none', borderRadius: 8, padding: '9px 14px', fontSize: 13.5, cursor: 'pointer', fontWeight: 600 } as CSSProperties,
  backBtn: { background: 'transparent', border: '1px solid var(--border, #d0d5dd)', borderRadius: 8, padding: '9px 14px', fontSize: 13.5, cursor: 'pointer', color: 'var(--text, #111)' } as CSSProperties,
  sheet: { background: '#fff', color: '#111', border: '1px solid #e5e7eb', borderRadius: 4, padding: '28px 32px', boxShadow: '0 1px 8px rgba(0,0,0,0.08)', fontSize: 13 } as CSSProperties,
  header: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', borderBottom: '2px solid #111', paddingBottom: 14, marginBottom: 18 } as CSSProperties,
  company: { fontSize: 18, fontWeight: 700, letterSpacing: -0.3 } as CSSProperties,
  companyMeta: { fontSize: 11, color: '#555', marginTop: 3 } as CSSProperties,
  docBox: { textAlign: 'right' } as CSSProperties,
  kind: { fontSize: 15, fontWeight: 700, letterSpacing: 0.5 } as CSSProperties,
  ref: { fontFamily: 'ui-monospace, monospace', fontSize: 13, marginTop: 2 } as CSSProperties,
  status: { display: 'inline-block', marginTop: 4, fontSize: 10.5, textTransform: 'uppercase', border: '1px solid #111', borderRadius: 999, padding: '1px 8px' } as CSSProperties,
  parties: { display: 'flex', gap: 24, marginBottom: 18 } as CSSProperties,
  party: { flex: 1 } as CSSProperties,
  partyHeading: { fontSize: 10.5, textTransform: 'uppercase', color: '#777', marginBottom: 4, letterSpacing: 0.5 } as CSSProperties,
  partyName: { fontWeight: 600, fontSize: 13.5 } as CSSProperties,
  partyLine: { fontSize: 12, color: '#444' } as CSSProperties,
  metaGrid: { display: 'flex', flexWrap: 'wrap', gap: '6px 28px', padding: '12px 0', borderTop: '1px solid #eee', borderBottom: '1px solid #eee', marginBottom: 16 } as CSSProperties,
  metaItem: { display: 'flex', flexDirection: 'column' } as CSSProperties,
  metaLabel: { fontSize: 10, textTransform: 'uppercase', color: '#888' } as CSSProperties,
  metaValue: { fontSize: 12.5, fontWeight: 500 } as CSSProperties,
  table: { width: '100%', borderCollapse: 'collapse', fontSize: 12.5, marginBottom: 14 } as CSSProperties,
  th: { textAlign: 'left', borderBottom: '1.5px solid #111', padding: '7px 8px', fontSize: 11, textTransform: 'uppercase', color: '#333' } as CSSProperties,
  thR: { textAlign: 'right', borderBottom: '1.5px solid #111', padding: '7px 8px', fontSize: 11, textTransform: 'uppercase', color: '#333' } as CSSProperties,
  td: { padding: '7px 8px', borderBottom: '1px solid #eee' } as CSSProperties,
  tdR: { padding: '7px 8px', borderBottom: '1px solid #eee', textAlign: 'right' } as CSSProperties,
  totals: { marginLeft: 'auto', width: 280 } as CSSProperties,
  totalRow: { display: 'flex', justifyContent: 'space-between', padding: '4px 8px', fontSize: 12.5 } as CSSProperties,
  totalRowStrong: { display: 'flex', justifyContent: 'space-between', padding: '7px 8px', fontSize: 14, fontWeight: 700, borderTop: '1.5px solid #111', marginTop: 2 } as CSSProperties,
  notes: { marginTop: 16, fontSize: 12, color: '#444', borderTop: '1px solid #eee', paddingTop: 10 } as CSSProperties,
  signs: { display: 'flex', gap: 40, marginTop: 40 } as CSSProperties,
  sign: { flex: 1 } as CSSProperties,
  signLine: { borderTop: '1px solid #111', marginBottom: 4 } as CSSProperties,
  signLabel: { fontSize: 11, color: '#666' } as CSSProperties,
  footer: { marginTop: 28, paddingTop: 10, borderTop: '1px solid #eee', fontSize: 10, color: '#999', textAlign: 'center' } as CSSProperties,
};
