'use client';
import { useCallback, useEffect, useState } from 'react';
import { CheckCheck, MessageCircleMore, Send } from 'lucide-react';
import styles from './my-work-center.module.css';
import { DISPLAY_LOCALE, DISPLAY_TIME_ZONE } from '@/lib/locale';

type Thread = { id: string; displayName: string; phone: string; unread: number; lastMessageAt: string | null; lastPreview: string | null; contactId: string | null; accountId: string | null };
type Message = { id: string; body: string; direction: 'inbound' | 'outbound'; status: string; occurredAt: string; sender: string };
const time = (v: string) => new Intl.DateTimeFormat(DISPLAY_LOCALE, { hour: '2-digit', minute: '2-digit', timeZone: DISPLAY_TIME_ZONE }).format(new Date(v));

export default function WhatsAppInbox({ initialThreads, initialThreadId = null }: { initialThreads: Thread[] | null; initialThreadId?: string | null }) {
  const [threads, setThreads] = useState(initialThreads ?? []); const [active, setActive] = useState<string | null>(initialThreadId ?? initialThreads?.[0]?.id ?? null); const [messages, setMessages] = useState<Message[]>([]); const [text, setText] = useState(''); const [configured, setConfigured] = useState<boolean | null>(null); const [error, setError] = useState<string | null>(null);
  const refresh = useCallback(async () => { const [t, s] = await Promise.all([fetch('/api/comms/whatsapp/threads', { cache: 'no-store' }), fetch('/api/comms/whatsapp/status', { cache: 'no-store' })]); if (t.ok) { const next = await t.json() as Thread[]; setThreads(next); setActive((current) => current && next.some((x) => x.id === current) ? current : next[0]?.id ?? null); } if (s.ok) setConfigured((await s.json()).configured === true); }, []);
  useEffect(() => { void refresh(); const source = typeof window !== 'undefined' ? new EventSource('/api/comms/whatsapp/stream') : null; source?.addEventListener('whatsapp', () => void refresh()); return () => source?.close(); }, [refresh]);
  useEffect(() => { if (!active) { setMessages([]); return; } void fetch(`/api/comms/whatsapp/threads/${encodeURIComponent(active)}/messages`, { cache: 'no-store' }).then(async (r) => { if (!r.ok) throw new Error('Unable to load conversation'); setMessages(await r.json() as Message[]); await fetch(`/api/comms/whatsapp/threads/${encodeURIComponent(active)}/read`, { method: 'POST' }); }).catch((e: Error) => setError(e.message)); }, [active]);
  async function send() { if (!active || !text.trim()) return; const body = text.trim(); setText(''); const r = await fetch(`/api/comms/whatsapp/threads/${encodeURIComponent(active)}/reply`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ text: body }) }); if (!r.ok) setError('Reply could not be sent. Check the WhatsApp Business connection.'); else { const m = await r.json() as Message; setMessages((old) => [...old, m]); void refresh(); } }
  if (configured === false && !threads.length) return <p className={styles.truth}><MessageCircleMore aria-hidden /><span>WhatsApp Business is not connected yet. Configure the official Meta Cloud API credentials and webhook URL, then conversations will appear here. Personal WhatsApp/Web sessions are not supported.</span></p>;
  return <div className={styles.columns} data-testid="whatsapp-inbox"><div className={styles.panel}><div className={styles.panelHead}><h2>WhatsApp</h2><span>{threads.reduce((n, t) => n + t.unread, 0)}</span></div><div className={styles.list}>{threads.length ? threads.map((t) => <button key={t.id} className={styles.row} onClick={() => setActive(t.id)} aria-pressed={active === t.id}><span className={styles.rowIcon}><MessageCircleMore /></span><span className={styles.rowMain}><strong>{t.displayName}</strong><small>{t.lastPreview ?? t.phone}</small></span>{t.unread ? <span className={styles.rowSide}>{t.unread}</span> : null}</button>) : <p className={styles.empty}>No WhatsApp conversations yet.</p>}</div></div><div className={styles.panel}><div className={styles.panelHead}><h2>{threads.find((t) => t.id === active)?.displayName ?? 'Conversation'}</h2><span>Cloud API</span></div><div className={styles.list}>{messages.map((m) => <div key={m.id} className={styles.row}><span className={styles.rowMain}><strong>{m.body}</strong><small>{m.direction === 'inbound' ? 'Customer' : 'You'} · {time(m.occurredAt)} {m.direction === 'outbound' ? `· ${m.status}` : ''}</small></span>{m.direction === 'outbound' && m.status === 'read' ? <CheckCheck aria-label="Read" /> : null}</div>)}{active ? <div style={{ display: 'flex', gap: 8, padding: 12 }}><input value={text} onChange={(e) => setText(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter') void send(); }} placeholder="Reply in WhatsApp" aria-label="WhatsApp reply" style={{ flex: 1 }} /><button type="button" onClick={() => void send()} aria-label="Send reply"><Send size={16} /></button></div> : <p className={styles.empty}>Select a conversation.</p>}{error ? <p className={styles.truth}>{error}</p> : null}</div></div></div>;
}
