// Shared helpers for the ADR tooling (adr-new + adr-check). No dependencies —
// the ADR folder is the source of truth; the registry (docs/adr/README.md) is
// rendered from it, so the two can never drift.
import { readFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url)); // scripts/
export const ADR_DIR = join(here, '..', 'docs', 'adr');
export const REGISTRY = join(ADR_DIR, 'README.md');

const FILE_RE = /^(\d{4})-.+\.md$/;
// Title line tolerates both separators used in the repo: "ADR-0001 — Title" and "ADR-0004: Title".
const TITLE_RE = /^#\s*ADR-(\d{4})\s*[—:-]\s*(.+?)\s*$/m;
const STATUS_RE = /\*\*Status:\*\*\s*([A-Za-z]+)/;
const DATE_RE = /\*\*Date:\*\*\s*(\d{4}-\d{2}-\d{2})|\((\d{4}-\d{2}-\d{2})\)/;

/** Read + parse every ADR file. Returns records sorted by number; `problems` lists parse errors. */
export function readAdrs() {
  const files = readdirSync(ADR_DIR)
    .filter((f) => FILE_RE.test(f))
    .sort();
  const adrs = [];
  const problems = [];
  for (const file of files) {
    const fileNum = file.match(FILE_RE)[1];
    const text = readFileSync(join(ADR_DIR, file), 'utf8');
    const title = text.match(TITLE_RE);
    if (!title) {
      problems.push(`${file}: missing/'# ADR-NNNN — Title' heading`);
      continue;
    }
    if (title[1] !== fileNum) {
      problems.push(`${file}: heading says ADR-${title[1]} but filename is ${fileNum}`);
    }
    const dateM = text.match(DATE_RE);
    adrs.push({
      num: fileNum,
      title: title[2].trim(),
      status: (text.match(STATUS_RE)?.[1] ?? 'Unknown').trim(),
      date: dateM ? dateM[1] ?? dateM[2] : '',
      file,
    });
  }
  adrs.sort((a, b) => a.num.localeCompare(b.num));
  return { adrs, problems };
}

/** The next free number (max + 1), zero-padded to 4. */
export function nextNumber(adrs) {
  const max = adrs.reduce((m, a) => Math.max(m, Number(a.num)), 0);
  return String(max + 1).padStart(4, '0');
}

/** kebab-case slug for a filename, from a free-text title. */
export function slugify(title) {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60);
}

/** Render the registry markdown from the ADR records (the single source of truth). */
export function renderRegistry(adrs) {
  const rows = adrs
    .map((a) => `| [${a.num}](${a.file}) | ${a.title} | ${a.status} | ${a.date || '—'} |`)
    .join('\n');
  return `# Architecture Decision Records — registry

<!-- GENERATED by \`pnpm adr:new\` / \`pnpm adr:check --write\`. Do not edit by hand;
     the ADR files in this folder are the source of truth. Run \`pnpm adr:new "<title>"\`
     to reserve the next number safely (never pick a number manually). -->

${adrs.length} decision${adrs.length === 1 ? '' : 's'}.

| # | Decision | Status | Date |
|--:|---|---|---|
${rows}
`;
}
