// Emit a Mermaid graph of the ADR relationships (supersedes = solid, related =
// dashed), coloured by status. Prints to stdout by default; `--write` saves it
// to docs/adr/GRAPH.md. Usage: pnpm adr:graph [--write]
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { ADR_DIR, readAdrs } from './adr-lib.mjs';

const { adrs } = readAdrs();
const lines = ['graph LR'];

for (const a of adrs) {
  const label = `${a.num}<br/>${a.title.length > 34 ? a.title.slice(0, 32) + '…' : a.title}`;
  lines.push(`  ${a.num}["${label}"]`);
}
for (const a of adrs) {
  for (const s of a.supersedes) lines.push(`  ${a.num} ==>|supersedes| ${s}`);
  for (const r of a.related) lines.push(`  ${a.num} -.-> ${r}`);
}
// status colouring
const cls = { Accepted: 'fill:#e8f5e9,stroke:#2e7d32', Superseded: 'fill:#f5f5f5,stroke:#9e9e9e,color:#9e9e9e', Deprecated: 'fill:#ffebee,stroke:#c62828', Draft: 'fill:#fff8e1,stroke:#f9a825', Proposed: 'fill:#e3f2fd,stroke:#1565c0' };
for (const [status, style] of Object.entries(cls)) {
  const ids = adrs.filter((a) => a.status === status).map((a) => a.num);
  if (ids.length) lines.push(`  classDef ${status.toLowerCase()} ${style};`, `  class ${ids.join(',')} ${status.toLowerCase()};`);
}

const mermaid = lines.join('\n');
const doc = `# ADR relationship graph

<!-- GENERATED by \`pnpm adr:graph --write\`. Solid = supersedes, dashed = related. -->

\`\`\`mermaid
${mermaid}
\`\`\`
`;

if (process.argv.includes('--write')) {
  writeFileSync(join(ADR_DIR, 'GRAPH.md'), doc);
  console.log('✓ Wrote docs/adr/GRAPH.md');
} else {
  console.log(doc);
}
