// @aura/sdk generator (gap register Vol 23 #21). Reads the OpenAPI document the API
// serves at /api/docs-json and regenerates packages/sdk/src/generated.ts — one typed
// method per operation, calling into the hand-written AuraHttp core (error taxonomy,
// idempotency, pagination types).
//
//   SPEC_URL=http://localhost:4200/api/docs-json node scripts/generate-sdk.mjs
//   node scripts/generate-sdk.mjs   # boots apps/api/dist/main.js (in-memory, no DB)
//
// The generated file is committed; CI regenerates it against the built API and fails
// on drift, so the published surface can never fall behind the routes.
import { spawn } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, '..');
const outFile = join(repo, 'packages', 'sdk', 'src', 'generated.ts');

async function fetchSpec() {
  if (process.env.SPEC_URL) {
    const res = await fetch(process.env.SPEC_URL);
    if (!res.ok) throw new Error(`SPEC_URL → ${res.status}`);
    return res.json();
  }
  // Boot the built API with no DATABASE_URL (in-memory adapters) on a scratch port.
  const port = 4977;
  const child = spawn(process.execPath, ['dist/main.js'], {
    cwd: join(repo, 'apps', 'api'),
    env: { ...process.env, PORT: String(port), DATABASE_URL: '', METRICS_ENABLED: '' },
    stdio: 'ignore',
  });
  try {
    let up = false;
    for (let i = 0; i < 60 && !up; i++) {
      up = await fetch(`http://localhost:${port}/api/v1/health`).then((r) => r.ok).catch(() => false);
      if (!up) await new Promise((r) => setTimeout(r, 1000));
    }
    if (!up) throw new Error('API did not become healthy — run `pnpm exec turbo run build --filter=@aura/api...` first');
    const res = await fetch(`http://localhost:${port}/api/docs-json`);
    if (!res.ok) throw new Error(`/api/docs-json → ${res.status}`);
    return await res.json();
  } finally {
    child.kill();
  }
}

/** `CrmAccountsController_list` → `crmAccountsList`; fallback derives from method+path. */
function methodName(op, method, path) {
  const raw = op.operationId
    ? op.operationId.replace(/Controller[_]?/, '_')
    : `${method}_${path}`;
  const name = raw
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part, i) => (i === 0 ? part.charAt(0).toLowerCase() + part.slice(1) : part.charAt(0).toUpperCase() + part.slice(1)))
    .join('');
  return name || 'call';
}

function generate(spec) {
  const lines = [];
  const used = new Set();
  const paths = Object.keys(spec.paths).sort();
  let count = 0;

  for (const rawPath of paths) {
    for (const method of ['get', 'post', 'put', 'patch', 'delete']) {
      const op = spec.paths[rawPath][method];
      if (!op) continue;
      // The client core prefixes /api/v1 — strip it from the spec path.
      const path = rawPath.replace(/^\/api\/v1/, '');
      if (path === '/health' && method !== 'get') continue;

      let name = methodName(op, method, path);
      while (used.has(name)) name += '_';
      used.add(name);
      count += 1;

      const pathParams = [...path.matchAll(/\{(\w+)\}/g)].map((m) => m[1]);
      const hasBody = ['post', 'put', 'patch'].includes(method);
      const queryParams = (op.parameters ?? []).filter((p) => p.in === 'query');

      const args = [
        ...pathParams.map((p) => `${p}: string`),
        ...(hasBody ? ['body?: unknown'] : []),
        ...(queryParams.length > 0 ? ['query?: Record<string, string | number | boolean | undefined>'] : []),
        'opts?: RequestOptions',
      ];
      const template = '`' + path.replace(/\{(\w+)\}/g, '${encodeURIComponent($1)}') + '`';
      const call = [
        `'${method.toUpperCase()}'`,
        template,
        hasBody ? 'body' : 'undefined',
        queryParams.length > 0 ? 'query' : 'undefined',
        'opts',
      ];
      lines.push(`  /** ${method.toUpperCase()} /api/v1${path} */`);
      lines.push(`  ${name}(${args.join(', ')}): Promise<unknown> {`);
      lines.push(`    return this.http.request(${call.join(', ')});`);
      lines.push('  }');
      lines.push('');
    }
  }

  return `// AUTO-GENERATED by scripts/generate-sdk.mjs — do not edit by hand.
// Source: the API's OpenAPI document (/api/docs-json). Regenerate: pnpm --filter @aura/sdk generate
// Operations: ${count}
import { AuraHttp, type AuraClientOptions, type RequestOptions } from './client';

export class AuraSdk {
  readonly http: AuraHttp;

  constructor(opts: AuraClientOptions) {
    this.http = new AuraHttp(opts);
  }

  /** Swap the bearer token (e.g. after authRefresh). */
  setToken(token: string | null): void {
    this.http.setToken(token);
  }

${lines.join('\n')}}
`;
}

const spec = await fetchSpec();
const code = generate(spec);
writeFileSync(outFile, code);
const ops = (code.match(/Operations: (\d+)/) ?? [])[1];
console.log(`✓ packages/sdk/src/generated.ts regenerated (${ops} operations).`);
