import 'reflect-metadata';
import { NestFactory } from '@nestjs/core';
import { ValidationPipe } from '@nestjs/common';
import { AccessService, AuthService, TenantContext, UsersService } from '@aura/core';
import request from 'supertest';
import * as XLSX from 'xlsx';
import { expect, it } from 'vitest';
import { AppModule } from '../src/app.module';
import { AllExceptionsFilter } from '../src/common/all-exceptions.filter';

/**
 * F-03 — NATIVE WORKBOOKS WITH TYPED VALUES, TOTALS, FILTERS, COMPLETE PERMITTED ROWS AND LINEAGE.
 * Auth ON, the shipped catalogue, in-memory stores; the screens are proved in the browser suite.
 */
const binary = (res: request.Response, done: (err: Error | null, body: Buffer) => void) => {
  const chunks: Buffer[] = [];
  res.on('data', (c: Buffer) => chunks.push(c));
  res.on('end', () => done(null, Buffer.concat(chunks)));
};
const about = (book: XLSX.WorkBook) => {
  const rows = XLSX.utils.sheet_to_json<string[]>(book.Sheets['About this export'], { header: 1 });
  return (name: string) => rows.find((row) => row[0] === name)?.[1];
};

it('F-03: the accounts register and the rows on screen both export as governed native workbooks', async () => {
  const previous = process.env.AUTH_JWT_SECRET;
  process.env.AUTH_JWT_SECRET = 'isolated-governed-workbook-secret';
  const app = await NestFactory.create(AppModule, { logger: ['error'] });
  app.setGlobalPrefix('api/v1');
  app.useGlobalPipes(new ValidationPipe({ transform: true, whitelist: true, forbidUnknownValues: false }));
  app.useGlobalFilters(new AllExceptionsFilter());
  const auth = app.get(AuthService);
  const tenant = app.get(TenantContext);
  const access = app.get(AccessService);
  const users = app.get(UsersService);
  app.use(async (req: { headers: { authorization?: string } }, res: { status: (n: number) => { end: () => void } }, next: () => void) => {
    const context = await auth.contextFromHeader(req.headers.authorization);
    if (!context) { res.status(401).end(); return; }
    tenant.run(context, next);
  });
  await app.init();
  try {
    expect(auth.enabled).toBe(true);
    const T = `workbook-${Date.now()}`;
    for (const [userId, roleId] of [['wb-admin', 'r-admin'], ['wb-sales', 'r-sales'], ['wb-finance', 'r-finance']]) {
      access.grant({ userId, roleId, scope: { kind: 'org', level: 'tenant', id: T } });
      users.save({ tenantId: T, userId, displayName: userId, active: true });
    }
    const as = (userId: string) => request.agent(app.getHttpServer()).set('Authorization', `Bearer ${auth.mint({ sub: userId, tenantId: T })}`);
    const admin = as('wb-admin');
    await admin.post('/api/v1/admin/settings').send({ key: 'company.legalName', value: 'Workbook Probe L.L.C.' }).expect(201);
    await admin.post('/api/v1/admin/settings').send({ key: 'company.trn', value: '100777777777777' }).expect(201);
    // More accounts than one page of the register holds, so completeness is read page by page.
    for (let i = 0; i < 503; i += 1) await admin.post('/api/v1/crm/accounts').send({ name: `Probe account ${String(i).padStart(3, '0')}` }).expect(201);

    // ── The register, complete, as Sales reads it ───────────────────────────────────────────────
    const register = await as('wb-sales').get('/api/v1/crm/accounts/export.xlsx').buffer(true).parse(binary).expect(200);
    const book = XLSX.read(register.body as Buffer, { type: 'buffer', cellNF: true });
    expect(book.SheetNames).toEqual(['Accounts', 'About this export']);
    const accounts = book.Sheets.Accounts;
    const data = XLSX.utils.sheet_to_json<Record<string, unknown>>(accounts);
    expect(data, 'all 503 — beyond the first page of 500').toHaveLength(503);
    expect(accounts['!autofilter']?.ref).toBe('A1:L504');
    expect(accounts.L2, '"Client since" is a date, not text').toMatchObject({ t: 'n', z: 'yyyy-mm-dd' });
    expect(accounts.C2, 'an absent party type is an empty cell').toBeUndefined();
    const field = about(book);
    expect(field('Completeness')).toBe('All 503 accounts in the register — every account you are permitted to see.');
    expect(field('Generated by')).toBe('wb-sales');
    expect(field('Issued under')).toBe('Workbook Probe L.L.C. · TRN 100777777777777');

    // ── The rows on screen, as Finance exports them ─────────────────────────────────────────────
    const shown = await as('wb-finance').post('/api/v1/documents/workbook').send({
      title: 'Salik charges', filename: 'salik-2026-10-02',
      columns: [
        { key: 'chargeDate', label: 'Date', type: 'date' },
        { key: 'gate', label: 'Gate' },
        { key: 'amount', label: 'Amount (AED)', type: 'money', total: true },
        { key: 'trips' },
      ],
      rows: [
        { chargeDate: '2026-09-30', gate: 'Al Barsha', amount: 4, trips: 1 },
        { chargeDate: '2026-10-01', gate: 'Garhoud', amount: 4.5, trips: 2 },
        { chargeDate: '2026-10-02', gate: 'Al Maktoum', amount: null, trips: 3 },
      ],
    }).buffer(true).parse(binary).expect(201);
    expect(shown.headers['content-disposition']).toContain('salik-2026-10-02.xlsx');
    const screen = XLSX.read(shown.body as Buffer, { type: 'buffer', cellFormula: true, cellNF: true });
    const sheet = screen.Sheets['Salik charges'];
    expect(sheet.A2).toMatchObject({ t: 'n', z: 'yyyy-mm-dd' });
    expect(sheet.C3).toMatchObject({ t: 'n', v: 4.5 });
    expect(sheet.D2, 'an undeclared column of numbers is read as numbers').toMatchObject({ t: 'n', v: 1 });
    expect(sheet.C5).toMatchObject({ t: 'n', v: 8.5, f: 'SUBTOTAL(109,C2:C4)' });
    expect(sheet.D5, 'only the declared column is totalled').toBeUndefined();
    expect(about(screen)('Completeness')).toBe('The 3 rows that were on screen when exported. This is what the page had loaded and filtered, which may not be the whole register.');

    // Bounds, and no session no workbook.
    await as('wb-finance').post('/api/v1/documents/workbook').send({ title: 'x', columns: [], rows: [] }).expect(400);
    await request(app.getHttpServer()).post('/api/v1/documents/workbook').send({ title: 'x', columns: [{ key: 'a' }], rows: [] }).expect(401);
  } finally {
    await app.close();
    if (previous === undefined) delete process.env.AUTH_JWT_SECRET; else process.env.AUTH_JWT_SECRET = previous;
  }
}, 120_000);
