import type { Pool } from 'pg';
import { newId, normalizeWhatsAppPhone, type WhatsAppMessageStatus, type WhatsAppMessageType } from '@aura/shared';
import type { NewWhatsAppMessage, StoredWhatsAppMessage, StoredWhatsAppThread, WhatsAppProviderAccount, WhatsAppStore } from './whatsapp-store';

type ThreadRow = { id: string; tenant_id: string; company_id: string | null; provider_account_id: string; phone_e164: string; display_name: string; external_conversation_id: string | null; contact_id: string | null; account_id: string | null; owner_user_id: string | null; unread_count: number; last_message_at: Date | string | null; last_preview: string | null };
type MessageRow = { id: string; tenant_id: string; company_id: string | null; provider_account_id: string; thread_id: string; external_message_id: string | null; direction: 'inbound' | 'outbound'; status: WhatsAppMessageStatus; message_type: WhatsAppMessageType; body: string; media_id: string | null; failed_reason: string | null; sender: string; occurred_at: Date | string; raw_payload: unknown };
const iso = (v: Date | string | null) => v ? (v instanceof Date ? v.toISOString() : new Date(v).toISOString()) : null;
const thread = (r: ThreadRow): StoredWhatsAppThread => ({ id: r.id, tenantId: r.tenant_id, companyId: r.company_id, providerAccountId: r.provider_account_id, channel: 'whatsapp', displayName: r.display_name, phone: r.phone_e164, externalConversationId: r.external_conversation_id, contactId: r.contact_id, accountId: r.account_id, ownerId: r.owner_user_id, unread: r.unread_count, lastMessageAt: iso(r.last_message_at), lastPreview: r.last_preview });
const message = (r: MessageRow): StoredWhatsAppMessage => ({ id: r.id, tenantId: r.tenant_id, companyId: r.company_id, providerAccountId: r.provider_account_id, threadId: r.thread_id, externalMessageId: r.external_message_id, direction: r.direction, status: r.status, type: r.message_type, body: r.body, mediaId: r.media_id, failedReason: r.failed_reason, sender: r.sender, occurredAt: iso(r.occurred_at)!, rawPayload: r.raw_payload });

export class PostgresWhatsAppStore implements WhatsAppStore {
  constructor(private readonly pool: Pool) {}
  async findProviderAccount(tenantId: string, externalAccountId: string): Promise<WhatsAppProviderAccount | null> {
    const r = await this.pool.query<{ id: string; tenant_id: string; company_id: string | null; external_account_id: string; owner_user_id: string | null; display_label: string; status: string }>(`select id,tenant_id,company_id,external_account_id,owner_user_id,display_label,status from public.aura_comms_accounts where tenant_id=$1 and channel='whatsapp' and external_account_id=$2 limit 1`, [tenantId, externalAccountId]);
    const x = r.rows[0]; return x ? { id: x.id, tenantId: x.tenant_id, companyId: x.company_id, externalAccountId: x.external_account_id, ownerUserId: x.owner_user_id, displayLabel: x.display_label, status: x.status } : null;
  }
  async findProviderAccountByExternalAccountId(externalAccountId: string): Promise<WhatsAppProviderAccount | null> {
    const r = await this.pool.query<{ id: string; tenant_id: string; company_id: string | null; external_account_id: string; owner_user_id: string | null; display_label: string; status: string }>(`select id,tenant_id,company_id,external_account_id,owner_user_id,display_label,status from public.aura_comms_accounts where channel='whatsapp' and external_account_id=$1 limit 1`, [externalAccountId]);
    const x = r.rows[0]; return x ? { id: x.id, tenantId: x.tenant_id, companyId: x.company_id, externalAccountId: x.external_account_id, ownerUserId: x.owner_user_id, displayLabel: x.display_label, status: x.status } : null;
  }
  async findThread(tenantId: string, id: string) { const r = await this.pool.query<ThreadRow>('select * from public.aura_comms_whatsapp_threads where tenant_id=$1 and id=$2', [tenantId, id]); return r.rows[0] ? thread(r.rows[0]) : null; }
  async findThreadByPhone(tenantId: string, providerAccountId: string, phone: string) { const r = await this.pool.query<ThreadRow>('select * from public.aura_comms_whatsapp_threads where tenant_id=$1 and provider_account_id=$2 and phone_e164=$3', [tenantId, providerAccountId, normalizeWhatsAppPhone(phone)]); return r.rows[0] ? thread(r.rows[0]) : null; }
  async ensureThread(input: Omit<StoredWhatsAppThread, 'unread' | 'lastMessageAt' | 'lastPreview'> & Partial<Pick<StoredWhatsAppThread, 'unread' | 'lastMessageAt' | 'lastPreview'>>) {
    const r = await this.pool.query<ThreadRow>(`insert into public.aura_comms_whatsapp_threads (id,tenant_id,company_id,provider_account_id,phone_e164,display_name,external_conversation_id,contact_id,account_id,owner_user_id,unread_count,last_message_at,last_preview) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) on conflict (tenant_id,provider_account_id,phone_e164) do update set display_name=coalesce(nullif(excluded.display_name,''),aura_comms_whatsapp_threads.display_name) returning *`, [input.id,input.tenantId,input.companyId,input.providerAccountId,normalizeWhatsAppPhone(input.phone),input.displayName,input.externalConversationId,input.contactId,input.accountId,input.ownerId,input.unread ?? 0,input.lastMessageAt,input.lastPreview]); return thread(r.rows[0]);
  }
  async listThreads(tenantId: string, companyId: string | null, ownerId?: string | null) { const p: unknown[] = [tenantId]; let sql = 'select * from public.aura_comms_whatsapp_threads where tenant_id=$1'; if (companyId !== null) { p.push(companyId); sql += ` and company_id=$${p.length}`; } if (ownerId) { p.push(ownerId); sql += ` and (owner_user_id is null or owner_user_id=$${p.length})`; } sql += ' order by last_message_at desc nulls last'; const r = await this.pool.query<ThreadRow>(sql, p); return r.rows.map(thread); }
  async listMessages(tenantId: string, threadId: string) { const r = await this.pool.query<MessageRow>('select * from public.aura_comms_whatsapp_messages where tenant_id=$1 and thread_id=$2 order by occurred_at', [tenantId, threadId]); return r.rows.map(message); }
  async getMessage(tenantId: string, messageId: string) { const r = await this.pool.query<MessageRow>('select * from public.aura_comms_whatsapp_messages where tenant_id=$1 and id=$2', [tenantId, messageId]); return r.rows[0] ? message(r.rows[0]) : null; }
  async findMessageByExternalId(tenantId: string, providerAccountId: string, externalMessageId: string) { const r = await this.pool.query<MessageRow>('select * from public.aura_comms_whatsapp_messages where tenant_id=$1 and provider_account_id=$2 and external_message_id=$3', [tenantId, providerAccountId, externalMessageId]); return r.rows[0] ? message(r.rows[0]) : null; }
  async insertMessage(input: NewWhatsAppMessage) { const r = await this.pool.query<MessageRow>(`insert into public.aura_comms_whatsapp_messages (id,tenant_id,company_id,provider_account_id,thread_id,external_message_id,direction,status,message_type,body,media_id,sender,occurred_at,raw_payload) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) on conflict (tenant_id,provider_account_id,external_message_id) do nothing returning *`, [newId(),input.tenantId,input.companyId,input.providerAccountId,input.threadId,input.externalMessageId,input.direction,input.status,input.type,input.body,input.mediaId ?? null,input.sender,input.occurredAt,input.rawPayload ?? null]); if (!r.rows[0] && input.externalMessageId) { const d = await this.pool.query<MessageRow>('select * from public.aura_comms_whatsapp_messages where tenant_id=$1 and provider_account_id=$2 and external_message_id=$3', [input.tenantId,input.providerAccountId,input.externalMessageId]); return { message: message(d.rows[0]), inserted: false }; } const m = message(r.rows[0]); await this.pool.query(`update public.aura_comms_whatsapp_threads set unread_count=unread_count+$2,last_message_at=$3,last_preview=$4,updated_at=now() where tenant_id=$1 and id=$5`, [input.tenantId,input.direction === 'inbound' ? 1 : 0,input.occurredAt,input.body.slice(0,240),input.threadId]); return { message: m, inserted: true }; }
  async updateStatus(tenantId: string, providerAccountId: string, externalMessageId: string, status: WhatsAppMessageStatus, failedReason: string | null = null) { const r = await this.pool.query<MessageRow>(`update public.aura_comms_whatsapp_messages set status=case when status='read' and $4 <> 'failed' then status when status='delivered' and $4 in ('received','queued','sent') then status when status='sent' and $4 in ('received','queued') then status else $4 end,failed_reason=$5 where tenant_id=$1 and provider_account_id=$2 and external_message_id=$3 returning *`, [tenantId,providerAccountId,externalMessageId,status,failedReason]); return r.rows[0] ? message(r.rows[0]) : null; }
  async setMessageDelivery(tenantId: string, messageId: string, externalMessageId: string | null, status: WhatsAppMessageStatus, failedReason: string | null = null) { const r = await this.pool.query<MessageRow>('update public.aura_comms_whatsapp_messages set external_message_id=$3,status=$4,failed_reason=$5 where tenant_id=$1 and id=$2 returning *', [tenantId,messageId,externalMessageId,status,failedReason]); return r.rows[0] ? message(r.rows[0]) : null; }
  async markRead(tenantId: string, threadId: string) { await this.pool.query('update public.aura_comms_whatsapp_threads set unread_count=0,updated_at=now() where tenant_id=$1 and id=$2', [tenantId,threadId]); await this.pool.query(`update public.aura_comms_whatsapp_messages set status='read' where tenant_id=$1 and thread_id=$2 and direction='inbound' and status <> 'read'`, [tenantId,threadId]); }
  async linkThread(tenantId: string, threadId: string, links: { contactId?: string | null; accountId?: string | null; ownerId?: string | null }) { const r = await this.pool.query<ThreadRow>('update public.aura_comms_whatsapp_threads set contact_id=$3,account_id=$4,owner_user_id=$5,updated_at=now() where tenant_id=$1 and id=$2 returning *', [tenantId,threadId,links.contactId ?? null,links.accountId ?? null,links.ownerId ?? null]); return r.rows[0] ? thread(r.rows[0]) : null; }
}
